services:
  app:
    container_name: amul_voice_app
    build: .
    ports:
      - "8003:8003"
    expose:
      - "8003"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis-stack
      - REDIS_PORT=6379
    restart: unless-stopped
    networks:
      - amul-network
      
networks:
  amul-network:
    external: true