services:
  app:
    container_name: bh_voice_app
    image: asia-south1-docker.pkg.dev/s-0-000236-99/moa-bharatvistaar-repo/bh-voice-api:09-latest
    ports:
      - "8003:8003"
    expose:
      - "8003"
    volumes:
      - .:/app
    env_file:
      - .env  
    restart: unless-stopped
    networks:
      - svanetwork
      
networks:
  svanetwork:
    external: true